name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Give execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Cache SonarQube dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - name: Install Sonar Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner.zip -d $HOME
          export PATH=$PATH:$HOME/sonar-scanner-4.6.2.2472-linux/bin
        
      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./gradlew build
          sonar-scanner \
          -Dsonar.projectKey=UndertaleGame \
          -Dsonar.sources=core/src/main/java \
          -Dsonar.java.binaries=core/build/classes \
          -Dsonar.host.url=http://localhost:9000
          -Dsonar.login=sqp_a5ae0f3c79d94ea2fb3c0a80ac7a63e3c0e395aa
